### ISSUE TITLE
Wallet connect popup and redirecting back to app.

### ISSUE THREAD

**Issue by chetu-ko** [WalletConnect/Web3ModalFlutter#105] opened 2024-03-26 06:42 UTC
Hi,

There are three minor issues that I have faced with SDK,

1. Not getting the connect wallet popup in the wallet application when the user tries to connect for the first time and needs to go back and press on try again, this happens whenever the user starts connecting for the first time. 
2. The next issue is sometimes not redirecting back to the app even if the wallet is connected to the wallet successfully, if we force back the wallet app the wallet is not connected.
3. Lastly, even when the wallet is successfully connected and redirected to the app bottom sheet window is still not closed automatically, 

Behaviour for 2nd and 3rd issue.
<img width="302" alt="Screenshot 2024-03-26 at 12 08 40 PM" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/60283981/5e69cf43-d532-4364-9cc3-518784493c8c">

The above issue only happens for the first time when the user opens the app and tries to connect the app to the wallet. This not exactly cause the issue making the user confused with the process.

Logs when the above 1.  issue happens.

> Pairing _onMessageEvent, Received data: {id: 1711433061125029, jsonrpc: 2.0, method: wc_pairingDelete, params: {message: User disconnected., code: 6000}}

Logs when the above 3.  issue happens.

> I/flutter ( 9438): [W3MService] _onRelayClientConnect: null

Usage code:
`W3MNetworkSelectButton(
                                              service: controller.w3mService!,
                                            )`

I am using the latest sdk of 13.1.2,

**Comment by quetool** [comment] 2024-03-26 08:34
Hello @chetu-ko, is this happening with every wallet? (Like Rainbow, Trust, Zerion, etc...)

Also, you say 
> I am using the latest sdk of 13.1.2

I suppose you are referring to MetasMask app version, right? Because we don't have such version for Web3Modal SDK

**Comment by chetu-ko** [comment] 2024-03-26 09:40
Thanks for your reply, sorry it's my bad.

> version is 3.1.2,

Yes, I only tried this with the metamask wallet app. Is there any issue with metamask.

**Comment by quetool** [comment] 2024-03-26 10:15
Could you please try the same with other wallets?

**Comment by chetu-ko** [comment] 2024-03-26 10:32
Yes, tried with trust after you saying, got the same error, you can see in the below attached image, I have connected with trust wallet and it's connected successfully, but pop up is still loading, waited for 5min.

<img width="310" alt="Screenshot 2024-03-26 at 4 00 38 PM" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/60283981/9d873ef6-0e54-4623-a7e5-4404818cfb06">

**Comment by chetu-ko** [comment] 2024-03-29 09:41
Hi @quetool any update on this?

**Comment by quetool** [comment] 2024-03-29 12:56
Hello @chetu-ko ! Can you provide a reproducible code? Everything is working well on my side.

**Comment by chetu-ko** [comment] 2024-04-01 05:21
`
 w3mService = W3MService(
      projectId: projectID
      metadata: PairingMetadata(
        name: AppName,
        description: AppDescription,
        url: AppURl
        icons: [AppIcon],
        redirect: const Redirect(
          native: 'flutterdapp://', // your own custom scheme
          universal: 'https://www.walletconnect.com',
        ),
      ),
    );

await w3mService!.init().then((value) {
      initdone.value = true;
      walletConnectionListner();
    });

 W3MNetworkSelectButton(
                                              service: controller.w3mService!,
                                            )

 walletConnectionListner() async {
    w3mService!.onModalConnect.subscribe((args) async {}

 w3mService!.onModalDisconnect.subscribe((args) async {}
}
`
I am just using the above code to get a wallet connection data not more than that, and I am making the necessary changes in the listener.

**Comment by chetu-ko** [comment] 2024-04-01 07:10
In the issues list 3rd one is fixed by adding a few lines of code below, I have added force close for bottom sheet model.

```
w3mService!.onModalConnect.subscribe((args) async {
   if (w3mService!.isOpen) {
       w3mService!.closeModal();
    }
}
```

**Comment by quetool** [comment] 2024-04-02 08:02
Hello @chetu-ko, without a complete reproducible code I can not help. A reproducible code doesn't have to be your very own code, you can write a new minimal reproducible code where I can reproduce the wrong behavior. For instance, if you clone this repo and run the example app, does it reproduces the issue?

**Comment by quetool** [comment] 2024-04-18 18:05
Hello @chetu-ko, I'll close this for now, please feel free to reopen if needed.

**Closed** 2024-04-18 18:05 UTC
