### ISSUE TITLE
[HELP] How to personal sign, make transaction with Coinbase ?

### ISSUE THREAD

**Issue by mthinh** [WalletConnect/Web3ModalFlutter#141] opened 2024-06-24 07:14 UTC
**Describe the bug**
I was able to connect coinbase, but cannot request a message signed
The error keeps saying `"No matching key. session topic doesn't exist: ` 
And I found out that cause we are connecting to coinbase data which does not contain topic

I'm currently using v.3.1.2

**Screenshots**
<img width="433" alt="Screenshot 2024-06-24 at 14 12 45" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/28992487/b575678e-e920-4771-9772-ae4e5a69040b">
<img width="434" alt="Screenshot 2024-06-24 at 14 13 52" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/28992487/7e91676a-1355-45ff-8bd0-1ceb441ebb0e">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by quetool** [comment] 2024-06-24 07:28
Hello @mthinh, can I see your implementation?

**Comment by mthinh** [comment] 2024-06-24 07:31
`
Future<String?> personalSign({
    required String message,
    required String wallet,
    String? chainId,
  }) async {
    await _w3mService.launchConnectedWallet();
    
    if (_w3mService.session?.sessionService.isCoinbase == true) {
      final data = await _w3mService.cbRequest(
        chainId: chainId ?? _currentWalletChainId ?? ETHEREUM.chainId,
        request: SessionRequestParams(
          method: 'personal_sign',
          params: [message, wallet],
        ),
      );
      if (data is String) return data;
      return null;
    }

    final data = await _app!.request(
      topic: _w3mService.session?.topic ?? '',
      chainId: chainId ?? _currentWalletChainId ?? ETHEREUM.chainId,
      request: SessionRequestParams(
        method: 'personal_sign',
        params: [message, wallet],
      ),
    );
    if (data is String) return data;

    return null;
  }
`
Thanks @quetool , I just found out that we always have cbRequest method to handle coinbase case

**Comment by quetool** [comment] 2024-06-24 07:33
cbRequest shouldn't be used and it will be deprecated soon. Let me take a look at your code.

**Comment by quetool** [comment] 2024-06-24 07:40
This is what you need to do. I added some explanatory comments.

```dart
Future<String?> personalSign({
  required String message,
  required String wallet,
}) async {
  _w3mService.launchConnectedWallet(); // you don't have to await this method

  // not sure why you used `_app!.request()` here, what is _app?
  final data = await _w3mService!.request(
    topic: _w3mService.session?.topic ?? '',
    // chainId chas to be always the current selected chain, otherwise request might not work on several wallets if the chain was not approved.
    chainId: _w3mService.selectedChain!.chainId,
    request: SessionRequestParams(
      method: 'personal_sign',
      params: [message, wallet],
    ),
  );
  if (data is String) return data;

  return null;
}
```

**Comment by mthinh** [comment] 2024-06-24 07:41
cool, thanks, let me try to
@quetool

**Comment by quetool** [comment] 2024-06-24 08:21
This is something on Coinbase side. Anyway this is not a `personal_sign`, right? Did the `personal_sign` example work? Any chance you can share the code for this transaction issue? I'm pretty sure it might be something wrong in the transaction object that Coinbase can't part properly.

**Comment by mthinh** [comment] 2024-06-24 08:23
@quetool , this is the code to make a transaction request, it works with other wallet (metamask, etc,..) but coinbase. 
Btw, sign transaction is working now. Thanks

**Comment by quetool** [comment] 2024-06-24 08:25
Wonderful! Would be interesting if could share the transaction object so I could debug and report to Coinbase if the issue is on their side

**Comment by mthinh** [comment] 2024-06-24 08:28
Hi @quetool , this is how transaction object looks like
<img width="474" alt="Screenshot 2024-06-24 at 15 27 41" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/28992487/7d4785e7-94db-4e05-bb2c-643ad8495de2">

**Comment by quetool** [comment] 2024-06-24 08:36
And is this not working? The only thing I see is the missing `0x` in the hex representation of the value but that shouldn't be an issue. It is weird anyway that is not added if you are using `.toJson()` method from `package:walletconnect_flutter_v2/apis/utils/extensions.dart`

**Comment by quetool** [comment] 2024-06-24 08:37
Please remove the `copyWith(data: transaction.data ?? '')` from transaction and try again.

**Comment by mthinh** [comment] 2024-06-24 08:42
If I remove it, will face this error, cause data is required as string
<img width="1349" alt="Screenshot 2024-06-24 at 15 41 15" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/28992487/a4d732ef-8b2f-444b-8ae5-8565baef7039">
![Uploading Screenshot 2024-06-24 at 15.41.54.png…]()

**Comment by mthinh** [comment] 2024-06-24 08:49
btw, Im using eth sepolia to test , also try data = `0x0` but no luck
<img width="468" alt="Screenshot 2024-06-24 at 15 49 36" src="https://github.com/WalletConnect/Web3ModalFlutter/assets/28992487/9de621c7-e6d2-4861-ba55-7b739f18415c">

**Comment by quetool** [comment] 2024-06-24 08:49
Seems like you are using and old version of our package. Could you please update to `web3modal_flutter: ^3.2.2`?

**Comment by mthinh** [comment] 2024-06-24 08:51
@quetool yes. currently using `3.1.2` cause I dont see any differences between 3.1.2 and 3.2.2 in term of coinbase stuff

**Comment by quetool** [comment] 2024-06-24 08:54
But there are :)
You can check coinbase_service here https://github.com/WalletConnect/Web3ModalFlutter/blob/master/lib/services/coinbase_service/coinbase_service.dart#L222

Several other bug fixes and new features were made in following versions https://pub.dev/packages/web3modal_flutter/changelog

I would totally update if I were you :)

**Comment by mthinh** [comment] 2024-06-24 08:55
@quetool sure ah, thanks, let me update and retry

**Comment by mthinh** [comment] 2024-06-24 09:06
Thanks @quetool , I can see transaction confirmation popup now. Thanks a lot for your great help 🙏

**Comment by quetool** [comment] 2024-06-24 09:07
Wonderful! I'll close the issue then! Thanks!

**Closed by quetool** 2024-06-24 09:07 UTC
